version: '0.9'

services:
  mysql:
    image: mysql
    container_name: LEGOInventorySqlContainer
    ports:
      - 3306:3306
    environment:
      DATABASE_NAME: LEGOSetInventory
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_USERNAME_PASSWORD}
    volumes:
      - ./project_resources:/var/lib/project_resources